'use client';

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

export default function ContractPrintPage() {
  const params = useParams();
  const id = params?.id as string | undefined;
  const [contract, setContract] = useState<any | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    let cancelled = false;

    async function load() {
      try {
        const res = await fetch(`/api/contracts/${id}`);
        if (!res.ok) {
          if (!cancelled) setContract(null);
          return;
        }
        const data = await res.json();
        if (!cancelled) setContract(data);
      } catch (e) {
        if (!cancelled) setContract(null);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white text-gray-500">
        Generating contract...
      </div>
    );
  }

  if (!contract) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white text-gray-500">
        Contract not found.
      </div>
    );
  }

  const createdDate = contract.createdAt
    ? new Date(contract.createdAt).toLocaleString('en-IN')
    : '';

  return (
    <div className="min-h-screen bg-white text-gray-900 p-8 print:p-4">
      <div className="max-w-2xl mx-auto border border-gray-300 rounded-lg p-8 shadow-md print:shadow-none">
        <header className="mb-6 border-b pb-4">
          <h1 className="text-2xl font-bold text-center mb-2">
            Forward Contract
          </h1>
          <p className="text-center text-sm text-gray-600">
            Contract ID: {contract.id}
          </p>
          {createdDate && (
            <p className="text-center text-xs text-gray-500">
              Created at: {createdDate}
            </p>
          )}
        </header>

        <section className="mb-6 space-y-2 text-sm">
          <h2 className="font-semibold text-base mb-2">Key Terms</h2>
          <p><span className="font-semibold">Crop:</span> {contract.crop}</p>
          <p><span className="font-semibold">Quantity:</span> {contract.quantity} {contract.unit}</p>
          <p><span className="font-semibold">Strike Price:</span> ₹{contract.strikePrice}/{contract.unit}</p>
          <p><span className="font-semibold">Delivery Window:</span> {contract.deliveryWindow}</p>
          <p><span className="font-semibold">Status:</span> {contract.status}</p>
        </section>

        <section className="mb-6 text-xs leading-relaxed text-gray-700">
          <h2 className="font-semibold text-sm mb-2">Summary</h2>
          <p>
            This contract records an agreement between the farmer and a counterparty
            to sell the above quantity of the specified crop at the given strike price
            within the delivery window. This prototype is part of the Krishi Hedge
            Smart India Hackathon 2025 solution.
          </p>
        </section>

        <section className="grid grid-cols-2 gap-8 mt-10 text-sm">
          <div className="border-t pt-4">
            <p className="font-semibold mb-8">Farmer Signature</p>
            <p className="text-xs text-gray-500">
              Name &amp; details recorded in system profile.
            </p>
          </div>
          <div className="border-t pt-4">
            <p className="font-semibold mb-8">Buyer / FPO Signature</p>
            <p className="text-xs text-gray-500">
              Counterparty identified in system records.
            </p>
          </div>
        </section>

        <footer className="mt-8 pt-4 border-t text-[10px] text-gray-500 flex justify-between">
          <span>Generated by Krishi Hedge</span>
          <span>For SIH 2025 demo use only</span>
        </footer>

        <div className="mt-6 text-center print:hidden">
          <button
            onClick={() => window.print()}
            className="inline-flex items-center px-4 py-2 bg-gray-900 text-white text-sm font-semibold rounded-md hover:bg-gray-800"
          >
            Print / Save as PDF
          </button>
        </div>
      </div>
    </div>
  );
}

